- name: Ensure app directory does not exist
  ansible.builtin.file:
    path: /home/ubuntu/app
    state: absent
  ignore_errors: true
  when: not (ansible_stat.stat.exists and ansible_stat.stat.isdir and ansible_stat.stat.path == "/home/ubuntu/app/letsencrypt")

- name: Ensure app directory exists
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Clone the application repository
  git:
    repo: 'https://github.com/onlydurodola/hng12-stage4-todo-app.git'
    dest: /home/ubuntu/app
    version: main
    force: yes

- name: Create letsencrypt directory
  file:
    path: /home/ubuntu/app/letsencrypt
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Build and deploy containers
  command: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/app/

