- name: Ensure app directory does not exist
  ansible.builtin.file:
    path: /home/ubuntu/app
    state: absent

- name: Ensure app directory exists
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Clone the application repository
  git:
    repo: 'https://github.com/onlydurodola/hng12-stage4-todo-app.git'
    dest: /home/ubuntu/app
    version: main
    force: yes

- name: Create letsencrypt directory
  file:
    path: /home/ubuntu/app/letsencrypt
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Build and deploy containers
  command: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/app/

- name: Wait for app to be accessible
  uri:
    url: "https://oluwatobiloba.tech"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 10
  delay: 10
